#!/usr/bin/env bash

# NOTE: can't use `nounset` here, as autogenerated setup.bash has
#       undeclared vars (AMENT_TRACE_SETUP_FILES)
set -o errexit

###ANCHOR

# setup ros2 environment
source "/opt/ros/${ROS_DISTRO}/setup.bash" --
exec "${@}"
