#!/usr/bin/env bash

# NOTE: can't use `nounset` here, as autogenerated setup.bash has
#       undeclared vars (AMENT_TRACE_SETUP_FILES)
set -o errexit

###BEFORE_ROS_DISTRO

# setup ros2 environment
source "/opt/ros/${ROS_DISTRO}/setup.bash" --

###AFTER_ROS_DISTRO

exec "${@}"
