# generated by datamodel-codegen:
#   filename:  gz_plugin_spec.json
#   version:   0.31.2

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel, Extra, Field

from .gz_topic_spec import GzTopicSpec


class GzPluginSpec(BaseModel):
    """
    Mapping from Gazebo plugin library file name to published topic specifications
    """

    class Config:
        extra = Extra.forbid
        allow_mutation = False

    plugin: str = Field(
        ..., description='Value of `filename` field in SDF plugin definition'
    )
    topics: Sequence[GzTopicSpec]
