# generated by datamodel-codegen:
#   filename:  gz_plugin_map.json
#   version:   0.31.2

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from .gz_plugin_spec import GzPluginSpec


class GzPluginMap(BaseModel):
    """
    List of gz plugin specifications
    """

    class Config:
        allow_mutation = False

    plugins: Sequence[GzPluginSpec] | None = None
