# generated by datamodel-codegen:
#   filename:  gz_plugin_spec.json
#   timestamp: 2025-07-03T01:12:15+00:00
#   version:   0.0.0

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra, Field

from .gz_topic_spec import GzTopicSpec


class GzPluginSpec(BaseModel):
    """
    Mapping from Gazebo plugin library file name to published topic specifications
    """

    class Config:
        extra = Extra.forbid
        allow_mutation = False

    plugin: Optional[str] = Field(
        None, description='Value of `filename` field in SDF plugin definition'
    )
    topics: List[GzTopicSpec]
