# generated by datamodel-codegen:
#   filename:  gz_sensor_map.json
#   version:   0.31.2

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from .gz_sensor_spec import GzSensorSpec


class GzSensorMap(BaseModel):
    """
    List of gz sensor specifications
    """

    class Config:
        allow_mutation = False

    sensors: Sequence[GzSensorSpec]
