# generated by datamodel-codegen:
#   filename:  gz_sensor_spec.json
#   timestamp: 2025-07-03T01:12:15+00:00
#   version:   0.0.0

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra, Field

from .gz_topic_spec import GzTopicSpec


class GzSensorSpec(BaseModel):
    """
    Specification of Gazebo sensor type name with published topic specifications
    """

    class Config:
        extra = Extra.forbid
        allow_mutation = False

    sensor: str = Field(
        ..., description='Value of `type` field in SDF sensor definition'
    )
    topics: List[GzTopicSpec]
    aliases: Optional[List[str]] = Field(
        [],
        description='Alternative sdf sensor type strings which map to this canonical sensor type',
        unique_items=True,
    )
    deprecated: Optional[bool] = Field(
        False,
        description='Boolean flag denoting deprecation status of the referenced sensor type',
    )
