# generated by datamodel-codegen:
#   filename:  gz_sensor_spec.json
#   version:   0.31.2

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel, Extra, Field

from .gz_topic_spec import GzTopicSpec


class GzSensorSpec(BaseModel):
    """
    Specification of Gazebo sensor type name with published topic specifications
    """

    class Config:
        extra = Extra.forbid
        allow_mutation = False

    sensor: str = Field(
        ..., description='Value of `type` field in SDF sensor definition'
    )
    topics: Sequence[GzTopicSpec]
    aliases: Sequence[str] | None = Field(
        [],
        description='Alternative sdf sensor type strings which map to this canonical sensor type',
        unique_items=True,
    )
    deprecated: bool | None = Field(
        False,
        description='Boolean flag denoting deprecation status of the referenced sensor type',
    )
