# generated by datamodel-codegen:
#   filename:  gz_sensor_map.json
#   timestamp: 2025-07-03T15:41:37+00:00
#   version:   0.31.2

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from .gz_sensor_spec import GzSensorSpec


class GzSensorMap(BaseModel):
    """
    List of gz sensor specifications
    """

    class Config:
        allow_mutation = False

    sensors: List[GzSensorSpec]
